
import React, { useState, useEffect } from 'react';
import { db } from '../db';
import { GameStatus } from '../types';
import { Trophy, Star, TrendingUp, LayoutGrid } from 'lucide-react';

const Dashboard: React.FC<{ onNavigate: (tab: string) => void }> = ({ onNavigate }) => {
  const [stats, setStats] = useState({
    totalGames: 0,
    completedGames: 0,
    pendingGames: 0,
    totalParticipants: 0,
    winnersByPos: { 1: 0, 2: 0, 3: 0, 4: 0 },
    topPerformers: [] as any[],
    categoryCounts: [] as { name: string, count: number }[]
  });

  useEffect(() => {
    const fetchStats = async () => {
      const games = await db.games.toArray();
      const participants = await db.participants.toArray();
      const gParticipants = await db.gameParticipants.toArray();
      const categories = await db.ageGroups.toArray();

      const winnersByPos = { 1: 0, 2: 0, 3: 0, 4: 0 };
      const winCounts: Record<number, number> = {};

      gParticipants.forEach(gp => {
        if (gp.position && gp.position >= 1 && gp.position <= 4) {
          winnersByPos[gp.position as keyof typeof winnersByPos]++;
          winCounts[gp.participantId] = (winCounts[gp.participantId] || 0) + 1;
        }
      });

      const allPerformers = Object.entries(winCounts)
        .map(([id, count]) => ({
          id: parseInt(id),
          count,
          name: participants.find(p => p.id === parseInt(id))?.name || 'Unknown'
        }))
        .sort((a, b) => b.count - a.count);

      const maxWins = allPerformers.length > 0 ? allPerformers[0].count : 0;
      const topPerformers = allPerformers.filter(p => p.count === maxWins && maxWins > 0);

      const catMap: Record<string, number> = { 'Open Matches': 0 };
      categories.forEach(c => catMap[c.name] = 0);
      
      games.forEach(g => {
        const catName = categories.find(c => c.id === g.ageGroupId)?.name || 'Open Matches';
        catMap[catName] = (catMap[catName] || 0) + 1;
      });

      const categoryCounts = Object.entries(catMap)
        .map(([name, count]) => ({ name, count }))
        .filter(c => c.count > 0);

      setStats({
        totalGames: games.length,
        completedGames: games.filter(g => g.status === GameStatus.COMPLETED).length,
        pendingGames: games.filter(g => g.status !== GameStatus.COMPLETED).length,
        totalParticipants: participants.length,
        winnersByPos,
        topPerformers,
        categoryCounts
      });
    };
    fetchStats();
  }, []);

//   const handleShare = async () => {
//     const settings = (await db.settings.toArray())[0];
//     const text = `🏡 Village: ${settings?.villageName || 'Our Village'}
// 🔥 Gang: ${settings?.gangName || 'Our Gang'}
// 📊 FESTIVAL SUMMARY
// --------------------
// Total Games: ${stats.totalGames}
// ✅ Finished: ${stats.completedGames}
// ⏳ Pending: ${stats.pendingGames}
// 👥 Total Participants: ${stats.totalParticipants}
// 🏆 Total Winners: ${(Object.values(stats.winnersByPos) as number[]).reduce((a: number, b: number) => a + b, 0)}

// GAMES BY CATEGORY:
// ${stats.categoryCounts.map(c => `- ${c.name}: ${c.count}`).join('\n')}

// Generated by Village Sports Manager`;

//     if (navigator.share) {
//       await navigator.share({ title: 'Festival Summary', text });
//     } else {
//       await navigator.clipboard.writeText(text);
//       alert('Summary copied to clipboard!');
//     }
//   };

  return (
    <div className="p-4 lg:p-8 space-y-6 bg-gray-50 min-h-full">
      <div className="flex items-center justify-between">
        {/* <h1 className="text-xl font-black text-gray-900 uppercase tracking-tight">Village Dashboard</h1> */}
        {/* <button 
          onClick={handleShare}
          className="bg-indigo-600 text-white px-4 py-2 rounded-xl flex items-center gap-2 font-bold shadow-lg active:scale-95 transition-all text-sm"
        >
          <Share2 size={16} /> <span>Share Summary</span>
        </button> */}
      </div>

      <div className="grid grid-cols-3 md:grid-cols-4 gap-3">
        <CompactStat label="Total Games" value={stats.totalGames} color="text-blue-600" />
        <CompactStat label="Finished" value={stats.completedGames} color="text-green-600" />
        <CompactStat label="Pending" value={stats.pendingGames} color="text-orange-600" />
        <div className="hidden md:flex">
          <CompactStat label="Participants" value={stats.totalParticipants} color="text-indigo-600" />
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-white p-6 rounded-3xl border border-gray-100 shadow-sm">
          <h2 className="text-sm font-black text-gray-400 uppercase tracking-widest mb-4 flex items-center gap-2">
            <LayoutGrid size={14} className="text-indigo-500" />
            Games by Category
          </h2>
          <div className="grid grid-cols-2 gap-3">
            {stats.categoryCounts.map(cat => (
              <div key={cat.name} className="p-3 bg-gray-50 rounded-2xl border border-gray-100 flex flex-col">
                <span className="text-[10px] font-black text-gray-400 uppercase truncate">{cat.name}</span>
                <span className="text-lg font-black text-gray-900">{cat.count}</span>
              </div>
            ))}
            {stats.categoryCounts.length === 0 && (
              <p className="col-span-2 py-4 text-center text-xs font-bold text-gray-400">No games created.</p>
            )}
          </div>
        </div>

        <div className="bg-white p-6 rounded-3xl border border-gray-100 shadow-sm">
          <h2 className="text-sm font-black text-gray-400 uppercase tracking-widest mb-4 flex items-center gap-2">
            <Trophy size={14} className="text-yellow-500" />
            Winners Summary
          </h2>
          <div className="grid grid-cols-2 gap-3">
            {[1, 2, 3, 4].map(pos => (
              <div key={pos} className="flex items-center justify-between px-4 py-3 bg-gray-50 rounded-2xl border border-gray-100">
                <span className="text-xs font-bold text-gray-500">{pos === 1 ? '1st' : pos === 2 ? '2nd' : pos === 3 ? '3rd' : '4th'}</span>
                <span className="font-black text-indigo-600">{stats.winnersByPos[pos as keyof typeof stats.winnersByPos]}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="bg-white p-6 rounded-3xl border border-gray-100 shadow-sm">
        <h2 className="text-sm font-black text-gray-400 uppercase tracking-widest mb-4 flex items-center gap-2">
          <TrendingUp size={14} className="text-green-500" />
          Top Performers (Highest Wins)
        </h2>
        <div className="flex flex-wrap gap-3">
          {stats.topPerformers.map((perf) => (
            <div key={perf.id} className="flex items-center gap-2 px-4 py-3 bg-indigo-50/50 rounded-2xl border border-indigo-100">
              <Star size={14} className="text-yellow-500" fill="currentColor" />
              <span className="text-sm font-bold text-gray-800">{perf.name}</span>
              <span className="text-[10px] font-black bg-white px-2 py-1 rounded-lg border border-indigo-100 text-indigo-700">{perf.count} Wins</span>
            </div>
          ))}
          {stats.topPerformers.length === 0 && (
            <p className="py-4 text-center text-xs font-bold text-gray-400 italic">No winners tracked yet</p>
          )}
        </div>
      </div>
    </div>
  );
};

const CompactStat: React.FC<{ label: string, value: number, color: string }> = ({ label, value, color }) => (
  <div className="p-4 rounded-2xl border border-gray-100 shadow-sm bg-white flex flex-col justify-center">
    <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-0.5">{label}</span>
    <span className={`text-xl font-black ${color}`}>{value}</span>
  </div>
);

export default Dashboard;