
import React, { useState, useEffect } from 'react';
import { db } from '../db';
import { type Game, GameStatus, type AgeGroup, type Participant, type GameParticipant } from '../types';
import { Plus, CheckCircle, Users, X, Search, Layers, Lock, Unlock, ShieldAlert, Share2 } from 'lucide-react';

const GamesList: React.FC = () => {
  const [games, setGames] = useState<Game[]>([]);
  const [participants, setParticipants] = useState<Participant[]>([]);
  const [gameParticipants, setGameParticipants] = useState<GameParticipant[]>([]);
  const [categories, setCategories] = useState<AgeGroup[]>([]);
  const [search, setSearch] = useState('');
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [selectedGame, setSelectedGame] = useState<Game | null>(null);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    const [g, p, gp, c] = await Promise.all([
      db.games.reverse().toArray(),
      db.participants.toArray(),
      db.gameParticipants.toArray(),
      db.ageGroups.toArray()
    ]);
    setGames(g);
    setParticipants(p);
    setGameParticipants(gp);
    setCategories(c);
  };

  const handleCreateGame = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const newGame: Game = {
      name: formData.get('name') as string,
      ageGroupId: parseInt(formData.get('ageGroupId') as string) || 0, 
      status: GameStatus.NOT_STARTED,
      isLocked: false
    };
    const id = await db.games.add(newGame);
    setGames([{ ...newGame, id }, ...games]);
    setIsCreateModalOpen(false);
  };

  const handleShare = async () => {
    const settings = (await db.settings.toArray())[0];
    const text = `🏡 Village: ${settings?.villageName || 'Our Village'}
🔥 Gang: ${settings?.gangName || 'Our Gang'}
🎮 GAMES LIST
--------------------
${games.map((g, i) => {
  const cat = categories.find(c => c.id === g.ageGroupId)?.name || 'Open Match';
  const status = g.status === GameStatus.COMPLETED ? '✅ Finished' : '⏳ Active';
  return `${i + 1}. ${g.name} (${cat}) - ${status}`;
}).join('\n')}
--------------------
Total Games: ${games.length}

Generated by Village Sports Manager`;

    if (navigator.share) {
      await navigator.share({ title: 'Games List', text });
    } else {
      await navigator.clipboard.writeText(text);
      alert('Games list copied to clipboard!');
    }
  };

  const filtered = games.filter(g => g.name.toLowerCase().includes(search.toLowerCase()));

  return (
    <div className="p-6 lg:p-10 bg-gray-50 min-h-full">
      <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 gap-4">
        <div>
          <h1 className="text-3xl font-black text-gray-900">Games</h1>
          <p className="text-gray-500 font-medium">Track and manage all festival events</p>
        </div>
        <div className="flex items-center gap-3">
          <button 
            onClick={handleShare}
            className="p-3.5 bg-white border border-gray-200 text-gray-600 rounded-2xl font-bold shadow-sm active:scale-95 transition-all flex items-center gap-2"
          >
            <Share2 size={20} />
          </button>
          <div className="relative">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
            <input 
              type="text" 
              placeholder="Search games..." 
              value={search}
              onChange={e => setSearch(e.target.value)}
              className="pl-11 pr-4 py-3 bg-white border border-gray-200 rounded-2xl outline-none focus:ring-2 focus:ring-indigo-500 font-medium w-full md:w-64 shadow-sm"
            />
          </div>
          <button onClick={() => setIsCreateModalOpen(true)} className="bg-indigo-600 text-white px-6 py-3.5 rounded-2xl font-bold shadow-xl flex items-center space-x-2 active:scale-95 transition-all">
            <Plus size={24} /> <span>New</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
        {filtered.map(game => (
          <div key={game.id} className="bg-white rounded-[2rem] shadow-sm border border-gray-100 overflow-hidden group hover:border-indigo-200 transition-all flex flex-col h-full">
            <div className="p-7 flex-1">
              <div className="flex justify-between items-start mb-3">
                {game.status === GameStatus.COMPLETED ? (
                  <span className="inline-flex items-center space-x-1 bg-green-50 text-green-700 px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-tight">
                    <CheckCircle size={12}/> <span>Finished</span>
                  </span>
                ) : (
                  <span className="inline-flex items-center space-x-1 bg-blue-50 text-blue-700 px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-tight">
                    <span>Active</span>
                  </span>
                )}
                <span className="text-[10px] font-black text-indigo-400 uppercase tracking-widest bg-indigo-50/50 px-2 py-0.5 rounded-md flex items-center gap-1">
                  <Layers size={10} />
                  {categories.find(c => c.id === game.ageGroupId)?.name || 'Open Match'}
                </span>
              </div>
              <h3 className="text-2xl font-black text-gray-900 mb-3 leading-tight">{game.name}</h3>
              <div className="flex items-center text-gray-400 font-bold space-x-2 mb-6">
                <Users size={18}/>
                <span>{gameParticipants.filter(gp => gp.gameId === game.id).length} Participants</span>
              </div>
            </div>
            <div className="px-7 pb-7">
              <button 
                onClick={() => setSelectedGame(game)} 
                className={`w-full py-4 rounded-2xl font-black transition-all flex items-center justify-center gap-2 ${
                  game.status === GameStatus.COMPLETED 
                    ? 'bg-gray-50 text-gray-500 hover:bg-gray-100' 
                    : 'bg-indigo-600 text-white shadow-lg hover:bg-indigo-700 active:scale-95'
                }`}
              >
                {game.status === GameStatus.COMPLETED ? <Lock size={18} /> : <Plus size={18} />}
                {game.status === GameStatus.COMPLETED ? 'LOCKED / VIEW' : 'ASSIGN WINNERS'}
              </button>
            </div>
          </div>
        ))}
        {filtered.length === 0 && (
          <div className="col-span-full py-20 text-center text-gray-400 font-bold italic">No games match your search.</div>
        )}
      </div>

      {isCreateModalOpen && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center p-6 z-[60]">
          <div className="bg-white rounded-3xl p-8 max-w-md w-full shadow-2xl animate-in zoom-in duration-200">
            <h2 className="text-2xl font-bold mb-6 text-gray-900">Create New Game</h2>
            <form onSubmit={handleCreateGame} className="space-y-6">
              <div>
                <label className="block text-sm font-bold text-gray-700 mb-2">Game Name</label>
                <input name="name" required className="w-full px-5 py-4 border-2 border-gray-100 rounded-xl bg-gray-50 font-bold outline-none focus:border-indigo-500" placeholder="e.g. Tug of War" />
              </div>
              <div>
                <label className="block text-sm font-bold text-gray-700 mb-2">Category</label>
                <select name="ageGroupId" className="w-full px-5 py-4 border-2 border-gray-100 rounded-xl bg-gray-50 font-bold outline-none focus:border-indigo-500">
                  <option value="0">Open Match (Everyone)</option>
                  {categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
                </select>
              </div>
              <div className="flex space-x-3 pt-4">
                <button type="button" onClick={() => setIsCreateModalOpen(false)} className="flex-1 py-4 font-bold text-gray-500 bg-gray-100 rounded-xl">Cancel</button>
                <button type="submit" className="flex-2 bg-indigo-600 text-white px-8 py-4 rounded-xl font-bold shadow-lg">Create</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {selectedGame && <GameManager game={selectedGame} onClose={() => setSelectedGame(null)} onFinish={() => fetchData()} />}
    </div>
  );
};

const GameManager: React.FC<{ game: Game, onClose: () => void, onFinish: () => void }> = ({ game, onClose, onFinish }) => {
  const [localGP, setLocalGP] = useState<any[]>([]);
  const [isFinishing, setIsFinishing] = useState(false);
  const [isUnlocked, setIsUnlocked] = useState(game.status !== GameStatus.COMPLETED);
  const [unlockModal, setUnlockModal] = useState(false);
  const [editorName, setEditorName] = useState('');
  const [editReason, setEditReason] = useState('');

  useEffect(() => {
    const fetch = async () => {
      const gps = await db.gameParticipants.where('gameId').equals(game.id!).toArray();
      const ps = await db.participants.toArray();
      setLocalGP(gps.map(gp => ({ 
        ...gp, 
        name: ps.find(p => p.id === gp.participantId)?.name || 'Unknown'
      })));
    };
    fetch();
  }, [game]);

  const handleFinish = async () => {
    if (game.status === GameStatus.COMPLETED && (!editorName || !editReason)) {
      alert("System Audit: Editor name and reason are required to modify finalized results.");
      return;
    }
    
    setIsFinishing(true);
    try {
      for (const gp of localGP) {
        const position = gp.position ? parseInt(gp.position) : undefined;
        await db.gameParticipants.update(gp.id!, { 
          position: (!isNaN(position as number) && (position as number) > 0) ? position : undefined 
        });
      }

      const actionType = game.status === GameStatus.COMPLETED ? 'EDIT' : 'END';
      
      await db.games.update(game.id!, { 
        status: GameStatus.COMPLETED, 
        isLocked: true, 
        endTime: game.endTime || Date.now() 
      });

      await db.history.add({ 
        gameId: game.id!, 
        actionType, 
        performedBy: editorName || 'Admin', 
        reason: editReason || 'Manual score finalization', 
        changes: `Winners recorded/updated for [${game.name}]`, 
        timestamp: Date.now() 
      });

      onFinish();
      onClose();
    } catch (err) {
      console.error(err);
      alert("Database error. Could not save winners.");
    } finally {
      setIsFinishing(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-white z-[70] flex flex-col overflow-hidden animate-in zoom-in duration-200">
      <div className={`p-6 flex justify-between items-center shadow-lg transition-colors ${isUnlocked ? 'bg-indigo-700 text-white' : 'bg-gray-800 text-white'}`}>
        <div>
          <h2 className="text-2xl font-black">{game.name}</h2>
          <p className="text-indigo-200 text-sm font-bold uppercase tracking-widest">{isUnlocked ? 'Assign Scores' : 'LOCKED - VIEW ONLY'}</p>
        </div>
        <button onClick={onClose}><X size={28}/></button>
      </div>

      <div className="flex-1 overflow-y-auto p-6 space-y-6 scrollbar-hide">
        {!isUnlocked && (
          <div className="bg-amber-50 border-2 border-amber-200 p-6 rounded-3xl flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-4">
              <ShieldAlert className="text-amber-600 shrink-0" size={32} />
              <div>
                <h4 className="font-black text-amber-900">Final Results Locked</h4>
                <p className="text-amber-700 text-sm font-medium">Scores are finalized. Unlocking will create an audit record of your changes.</p>
              </div>
            </div>
            <button 
              onClick={() => setUnlockModal(true)}
              className="w-full md:w-auto bg-amber-600 text-white px-8 py-3.5 rounded-2xl font-black flex items-center justify-center gap-2 shadow-lg shadow-amber-200 active:scale-95 transition-all"
            >
              <Unlock size={20} /> UNLOCK BOARD
            </button>
          </div>
        )}

        <div className="bg-white rounded-[2rem] border border-gray-100 shadow-sm overflow-hidden">
          <table className="w-full text-left">
            <thead className="bg-gray-50 text-[10px] font-black uppercase text-gray-400 tracking-widest border-b">
              <tr><th className="px-8 py-5">Participant</th><th className="px-8 py-5 text-center w-32">Position (Rank)</th></tr>
            </thead>
            <tbody className="divide-y divide-gray-50 font-medium">
              {localGP.map(p => (
                <tr key={p.participantId} className="hover:bg-gray-50/50 transition-colors">
                  <td className="px-8 py-6">
                    <div className="flex items-center gap-3">
                      <div className="w-9 h-9 rounded-xl bg-indigo-50 flex items-center justify-center text-indigo-400 font-bold text-xs">{p.name.charAt(0)}</div>
                      <span className="font-bold text-gray-900 text-lg">{p.name}</span>
                    </div>
                  </td>
                  <td className="px-8 py-6">
                    <input 
                      type="number" 
                      min="1" 
                      max="100"
                      disabled={!isUnlocked} 
                      value={p.position || ''} 
                      onChange={(e) => setLocalGP(prev => prev.map(item => item.id === p.id ? {...item, position: e.target.value} : item))} 
                      className={`w-24 mx-auto block px-4 py-3.5 border-2 rounded-2xl font-black text-center outline-none transition-all ${!isUnlocked ? 'bg-gray-100 border-transparent text-gray-400 cursor-not-allowed' : 'bg-white border-gray-100 text-indigo-600 focus:border-indigo-500 shadow-inner'}`} 
                      placeholder="-" 
                    />
                  </td>
                </tr>
              ))}
              {localGP.length === 0 && (
                <tr><td colSpan={2} className="px-8 py-20 text-center text-gray-400 font-bold italic text-lg">No participants have been registered for this event.</td></tr>
              )}
            </tbody>
          </table>
        </div>

        {isUnlocked && game.status === GameStatus.COMPLETED && (
          <div className="bg-red-50 p-6 rounded-[2rem] border border-red-100 space-y-4">
            <h4 className="text-xs font-black text-red-600 uppercase tracking-widest flex items-center gap-2">
              <ShieldAlert size={16} /> Audit Validation Required
            </h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-1">
                <span className="text-[10px] font-black text-red-400 uppercase px-1">Editor Name</span>
                <input 
                  placeholder="e.g. Festival Head" 
                  value={editorName} 
                  onChange={e => setEditorName(e.target.value)} 
                  className="w-full px-5 py-4 bg-white border border-red-100 rounded-2xl outline-none font-bold focus:border-red-400"
                />
              </div>
              <div className="space-y-1">
                <span className="text-[10px] font-black text-red-400 uppercase px-1">Reason for Adjustment</span>
                <input 
                  placeholder="e.g. Correcting clerical error" 
                  value={editReason} 
                  onChange={e => setEditReason(e.target.value)} 
                  className="w-full px-5 py-4 bg-white border border-red-100 rounded-2xl outline-none font-bold focus:border-red-400"
                />
              </div>
            </div>
          </div>
        )}
      </div>

      <div className="p-8 border-t bg-white flex flex-col md:flex-row gap-4">
        <button onClick={onClose} className="flex-1 py-5 font-black text-gray-400 bg-gray-50 rounded-[1.5rem] hover:bg-gray-100 transition-colors uppercase tracking-widest">Close</button>
        {isUnlocked && (
          <button 
            onClick={handleFinish} 
            disabled={isFinishing}
            className="flex-[2] bg-indigo-600 text-white py-5 rounded-[1.5rem] font-black shadow-2xl shadow-indigo-200 active:scale-95 transition-all disabled:opacity-50 uppercase tracking-widest"
          >
            {isFinishing ? 'Processing...' : 'Save Changes & Finalize🏅'}
          </button>
        )}
      </div>

      {unlockModal && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-md flex items-center justify-center p-6 z-[80] animate-in fade-in duration-300">
          <div className="bg-white rounded-[2.5rem] p-10 max-w-sm w-full shadow-2xl text-center">
            <div className="w-20 h-20 bg-amber-100 rounded-full flex items-center justify-center mx-auto mb-6">
              <Unlock className="text-amber-600" size={40} />
            </div>
            <h3 className="text-2xl font-black text-gray-900 mb-3">Unlock Board?</h3>
            <p className="text-gray-500 mb-8 font-medium leading-relaxed">This action will be tracked in the audit history. Are you sure you need to modify finalized results?</p>
            <div className="flex flex-col gap-3">
              <button onClick={() => { setIsUnlocked(true); setUnlockModal(false); }} className="w-full bg-indigo-600 text-white py-5 rounded-2xl font-black shadow-xl">Yes, I need to edit</button>
              <button onClick={() => setUnlockModal(false)} className="w-full py-4 font-bold text-gray-400 hover:text-gray-600">No, go back</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default GamesList;
