
import React, { useState, useEffect } from 'react';
import { db } from '../db';
import type { Participant, AgeGroup, Game } from '../types';
import { Search, UserPlus, Medal, Star, Users, Edit2, ListPlus, CheckSquare, X, ChevronRight, Layers, Share2 } from 'lucide-react';

const ParticipantsList: React.FC = () => {
  const [participants, setParticipants] = useState<Participant[]>([]);
  const [ageGroups, setAgeGroups] = useState<AgeGroup[]>([]);
  const [games, setGames] = useState<Game[]>([]);
  const [search, setSearch] = useState('');
  const [selectedAgeGroup, setSelectedAgeGroup] = useState<number | 'all'>('all');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingParticipant, setEditingParticipant] = useState<Participant | null>(null);
  const [selectedIds, setSelectedIds] = useState<Set<number>>(new Set());
  const [isGameAssignModalOpen, setIsGameAssignModalOpen] = useState(false);
  const [editorName, setEditorName] = useState('');
  const [editReason, setEditReason] = useState('');

  useEffect(() => {
    const fetch = async () => {
      const [p, a, g] = await Promise.all([
        db.participants.toArray(),
        db.ageGroups.toArray(),
        db.games.toArray()
      ]);
      setParticipants(p);
      setAgeGroups(a);
      setGames(g);
    };
    fetch();
  }, []);

  const handleShare = async () => {
    const settings = (await db.settings.toArray())[0];
    let text = `🏡 Village: ${settings?.villageName || 'Our Village'}
🔥 Gang: ${settings?.gangName || 'Our Gang'}
👥 PARTICIPANTS LIST
--------------------`;

    for (const group of ageGroups) {
      const gParticipants = participants.filter(p => p.ageGroupId === group.id);
      if (gParticipants.length > 0) {
        text += `\n\n[${group.name.toUpperCase()}]`;
        gParticipants.forEach((p, i) => {
          text += `\n${i + 1}. ${p.name}`;
        });
      }
    }

    const unassigned = participants.filter(p => !p.ageGroupId);
    if (unassigned.length > 0) {
      text += `\n\n[UNASSIGNED]`;
      unassigned.forEach((p, i) => {
        text += `\n${i + 1}. ${p.name}`;
      });
    }

    text += `\n\nTotal Participants: ${participants.length}\nGenerated by Village Sports Manager`;

    if (navigator.share) {
      await navigator.share({ title: 'Participants List', text });
    } else {
      await navigator.clipboard.writeText(text);
      alert('Participants list copied to clipboard!');
    }
  };

  const toggleSelection = (id: number) => {
    const newSelection = new Set(selectedIds);
    if (newSelection.has(id)) newSelection.delete(id);
    else newSelection.add(id);
    setSelectedIds(newSelection);
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const name = formData.get('name') as string;
    const ageGroupId = parseInt(formData.get('ageGroup') as string);

    if (editingParticipant) {
      if (!editorName || !editReason) { alert("Auditor name and reason are required."); return; }
      await db.participants.update(editingParticipant.id!, { name, ageGroupId });
      await db.history.add({
        actionType: 'EDIT', performedBy: editorName, reason: editReason,
        changes: `Participant [${editingParticipant.name}] profile updated.`, timestamp: Date.now()
      });
      setParticipants(participants.map(p => p.id === editingParticipant.id ? { ...p, name, ageGroupId } : p));
    } else {
      const id = await db.participants.add({ name, ageGroupId, badgeCount: 0, points: 0 });
      setParticipants([...participants, { name, ageGroupId, badgeCount: 0, points: 0, id }]);
    }
    setIsModalOpen(false);
  };

  const assignToGame = async (gameId: number) => {
    for (const pId of selectedIds) {
      const exists = await db.gameParticipants.where({ gameId, participantId: pId }).count();
      if (!exists) await db.gameParticipants.add({ gameId, participantId: pId });
    }
    setSelectedIds(new Set());
    setIsGameAssignModalOpen(false);
    alert(`Added ${selectedIds.size} participants to game!`);
  };

  const filtered = participants.filter(p => {
    const matchesSearch = p.name.toLowerCase().includes(search.toLowerCase());
    const matchesGroup = selectedAgeGroup === 'all' || p.ageGroupId === selectedAgeGroup;
    return matchesSearch && matchesGroup;
  });

  return (
    <div className="p-6 lg:p-10 bg-gray-50 min-h-full pb-32">
      <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 gap-4">
        <div>
          <h1 className="text-3xl font-black text-gray-900">Participants</h1>
          <p className="text-gray-500 font-medium">Manage all registered festival athletes</p>
        </div>
        <div className="flex items-center gap-3">
          <button 
            onClick={handleShare}
            className="p-4 bg-white border border-gray-200 text-gray-600 rounded-2xl font-bold shadow-sm active:scale-95 transition-all flex items-center gap-2"
          >
            <Share2 size={20} />
          </button>
          <button onClick={() => { setEditingParticipant(null); setIsModalOpen(true); }} className="bg-indigo-600 text-white px-6 py-4 rounded-2xl font-bold shadow-xl flex items-center justify-center space-x-2 active:scale-95 transition-all">
            <UserPlus size={22} /> <span>Add Participant</span>
          </button>
        </div>
      </div>

      <div className="mb-6">
        <div className="relative mb-6">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
          <input type="text" placeholder="Search by name..." className="w-full pl-12 pr-5 py-4 border-2 border-gray-100 rounded-2xl bg-white focus:ring-2 focus:ring-indigo-500 outline-none font-medium" value={search} onChange={e => setSearch(e.target.value)} />
        </div>

        <div className="flex overflow-x-auto space-x-2 pb-2 scrollbar-hide">
          <button onClick={() => setSelectedAgeGroup('all')} className={`px-6 py-3 rounded-xl font-bold transition-all whitespace-nowrap ${selectedAgeGroup === 'all' ? 'bg-indigo-600 text-white shadow-lg' : 'bg-white text-gray-500 border border-gray-100 hover:border-indigo-100'}`}>All Categories</button>
          {ageGroups.map(a => (
            <button key={a.id} onClick={() => setSelectedAgeGroup(a.id!)} className={`px-6 py-3 rounded-xl font-bold transition-all whitespace-nowrap ${selectedAgeGroup === a.id ? 'bg-indigo-600 text-white shadow-lg' : 'bg-white text-gray-500 border border-gray-100 hover:border-indigo-100'}`}>{a.name}</button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4 gap-6">
        {filtered.map(p => (
          <div key={p.id} className={`bg-white p-6 rounded-3xl shadow-sm border-2 transition-all ${selectedIds.has(p.id!) ? 'border-indigo-600 ring-4 ring-indigo-50' : 'border-gray-100'}`}>
            <div className="flex items-start justify-between mb-4">
              <div className="flex items-center space-x-3">
                <button onClick={() => toggleSelection(p.id!)} className={`w-8 h-8 rounded-lg flex items-center justify-center border-2 transition-all ${selectedIds.has(p.id!) ? 'bg-indigo-600 border-indigo-600 text-white' : 'border-gray-200 text-transparent'}`}><CheckSquare size={18} /></button>
                <div className="w-12 h-12 bg-indigo-50 rounded-xl flex items-center justify-center text-indigo-600 font-black text-xl uppercase">{p.name.charAt(0)}</div>
              </div>
              <button onClick={() => { setEditingParticipant(p); setIsModalOpen(true); }} className="p-2 text-gray-400 hover:text-indigo-600 rounded-lg"><Edit2 size={18} /></button>
            </div>
            <h3 className="text-xl font-bold text-gray-900 truncate">{p.name}</h3>
            <div className="flex items-center gap-1.5 text-gray-500 font-bold text-sm">
              <Layers size={14} className="text-gray-400" />
              <span>{ageGroups.find(a => a.id === p.ageGroupId)?.name || 'Unassigned'}</span>
            </div>
          </div>
        ))}
        {filtered.length === 0 && (
          <div className="col-span-full py-20 text-center text-gray-400 font-bold italic">No participants found.</div>
        )}
      </div>

      {selectedIds.size > 0 && (
        <div className="fixed bottom-24 lg:bottom-10 left-1/2 -translate-x-1/2 bg-indigo-900 text-white px-8 py-5 rounded-[2rem] shadow-2xl flex items-center space-x-6 z-50 animate-in slide-in-from-bottom duration-300">
          <span className="font-bold border-r border-indigo-700 pr-6">{selectedIds.size} Selected</span>
          <button onClick={() => setIsGameAssignModalOpen(true)} className="flex items-center space-x-2 bg-white text-indigo-900 px-6 py-2.5 rounded-xl font-black"><ListPlus size={20} /> <span>Assign to Game</span></button>
          <button onClick={() => setSelectedIds(new Set())}><X size={24} /></button>
        </div>
      )}

      {isGameAssignModalOpen && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center p-6 z-[60]">
          <div className="bg-white rounded-3xl p-8 max-w-lg w-full shadow-2xl flex flex-col max-h-[80vh]">
            <h2 className="text-2xl font-bold mb-6">Assign {selectedIds.size} to Game</h2>
            <div className="overflow-y-auto space-y-3 flex-1 scrollbar-hide">
              {games.map(game => (
                <button key={game.id} onClick={() => assignToGame(game.id!)} className="w-full text-left p-5 rounded-2xl border-2 border-gray-100 hover:border-indigo-600 transition-all flex justify-between items-center group">
                  <div className="flex flex-col">
                    <h4 className="font-bold text-gray-900 group-hover:text-indigo-700 transition-colors">{game.name}</h4>
                    <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest">
                      {ageGroups.find(a => a.id === game.ageGroupId)?.name || 'Open Match'}
                    </span>
                  </div>
                  <ChevronRight size={18} className="text-gray-300 group-hover:text-indigo-600 transition-colors" />
                </button>
              ))}
              {games.length === 0 && (
                <div className="text-center py-10 text-gray-400 font-bold">No games available. Create one first!</div>
              )}
            </div>
            <button onClick={() => setIsGameAssignModalOpen(false)} className="mt-6 w-full py-4 font-bold text-gray-500 bg-gray-100 rounded-xl">Cancel</button>
          </div>
        </div>
      )}

      {isModalOpen && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center p-6 z-[60]">
          <div className="bg-white rounded-3xl p-8 max-w-md w-full animate-in zoom-in duration-200">
            <h2 className="text-2xl font-bold mb-6">{editingParticipant ? 'Edit' : 'Add'} Participant</h2>
            <form onSubmit={handleSubmit} className="space-y-6">
              <div>
                <label className="block text-sm font-bold text-gray-700 mb-2">Full Name</label>
                <input name="name" required defaultValue={editingParticipant?.name} className="w-full px-5 py-4 border-2 border-gray-100 rounded-xl bg-gray-50 font-bold outline-none focus:border-indigo-500" placeholder="e.g. John Doe" />
              </div>
              <div>
                <label className="block text-sm font-bold text-gray-700 mb-2">Category</label>
                <select name="ageGroup" required defaultValue={editingParticipant?.ageGroupId} className="w-full px-5 py-4 border-2 border-gray-100 rounded-xl bg-gray-50 font-bold outline-none focus:border-indigo-500">
                  <option value="" disabled>Select Category</option>
                  {ageGroups.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}
                </select>
              </div>
              {editingParticipant && (
                <div className="bg-indigo-50/50 p-4 rounded-2xl border border-indigo-100 space-y-4">
                  <p className="text-[10px] font-black text-indigo-400 uppercase tracking-widest">Auditor Information</p>
                  <input value={editorName} onChange={e => setEditorName(e.target.value)} required className="w-full px-4 py-3 border border-gray-200 rounded-xl bg-white outline-none" placeholder="Who is editing?" />
                  <input value={editReason} onChange={e => setEditReason(e.target.value)} required className="w-full px-4 py-3 border border-gray-200 rounded-xl bg-white outline-none" placeholder="Why is this being edited?" />
                </div>
              )}
              <div className="flex space-x-3 pt-4">
                <button type="button" onClick={() => setIsModalOpen(false)} className="flex-1 py-4 font-bold text-gray-500 bg-gray-100 rounded-xl">Cancel</button>
                <button type="submit" className="flex-2 bg-indigo-600 text-white px-8 py-4 rounded-xl font-bold shadow-lg">Save</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default ParticipantsList;
